"""Add category to expenses

Revision ID: 181c739d87e8
Revises: 7e78f5456d9b
Create Date: 2026-01-04 08:07:08.835368

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '181c739d87e8'
down_revision: Union[str, Sequence[str], None] = '7e78f5456d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.String(), server_default='cash', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###
